export const BIBLE_METADATA = {
  en: {
    old: [
      { id: 'gen', name: 'Genesis', chapters: 50 },
      { id: 'exo', name: 'Exodus', chapters: 40 },
      { id: 'lev', name: 'Leviticus', chapters: 27 },
      { id: 'num', name: 'Numbers', chapters: 36 },
      { id: 'deu', name: 'Deuteronomy', chapters: 34 },
      { id: 'jos', name: 'Joshua', chapters: 24 },
      { id: 'jud', name: 'Judges', chapters: 21 },
      { id: 'rut', name: 'Ruth', chapters: 4 },
      { id: '1sa', name: '1 Samuel', chapters: 31 },
      { id: '2sa', name: '2 Samuel', chapters: 24 },
      { id: '1ki', name: '1 Kings', chapters: 22 },
      { id: '2ki', name: '2 Kings', chapters: 25 },
      { id: '1ch', name: '1 Chronicles', chapters: 29 },
      { id: '2ch', name: '2 Chronicles', chapters: 36 },
      { id: 'ezr', name: 'Ezra', chapters: 10 },
      { id: 'neh', name: 'Nehemiah', chapters: 13 },
      { id: 'est', name: 'Esther', chapters: 10 },
      { id: 'job', name: 'Job', chapters: 42 },
      { id: 'psa', name: 'Psalms', chapters: 150 },
      { id: 'pro', name: 'Proverbs', chapters: 31 },
      { id: 'ecc', name: 'Ecclesiastes', chapters: 12 },
      { id: 'sos', name: 'Song of Solomon', chapters: 8 },
      { id: 'isa', name: 'Isaiah', chapters: 66 },
      { id: 'jer', name: 'Jeremiah', chapters: 52 },
      { id: 'lam', name: 'Lamentations', chapters: 5 },
      { id: 'eze', name: 'Ezekiel', chapters: 48 },
      { id: 'dan', name: 'Daniel', chapters: 12 },
      { id: 'hos', name: 'Hosea', chapters: 14 },
      { id: 'joe', name: 'Joel', chapters: 3 },
      { id: 'amo', name: 'Amos', chapters: 9 },
      { id: 'oba', name: 'Obadiah', chapters: 1 },
      { id: 'jon', name: 'Jonah', chapters: 4 },
      { id: 'mic', name: 'Micah', chapters: 7 },
      { id: 'nah', name: 'Nahum', chapters: 3 },
      { id: 'hab', name: 'Habakkuk', chapters: 3 },
      { id: 'zep', name: 'Zephaniah', chapters: 3 },
      { id: 'hag', name: 'Haggai', chapters: 2 },
      { id: 'zec', name: 'Zechariah', chapters: 14 },
      { id: 'mal', name: 'Malachi', chapters: 4 }
    ],
    new: [
      { id: 'mat', name: 'Matthew', chapters: 28 },
      { id: 'mar', name: 'Mark', chapters: 16 },
      { id: 'luk', name: 'Luke', chapters: 24 },
      { id: 'joh', name: 'John', chapters: 21 },
      { id: 'act', name: 'Acts', chapters: 28 },
      { id: 'rom', name: 'Romans', chapters: 16 },
      { id: '1co', name: '1 Corinthians', chapters: 16 },
      { id: '2co', name: '2 Corinthians', chapters: 13 },
      { id: 'gal', name: 'Galatians', chapters: 6 },
      { id: 'eph', name: 'Ephesians', chapters: 6 },
      { id: 'phi', name: 'Philippians', chapters: 4 },
      { id: 'col', name: 'Colossians', chapters: 4 },
      { id: '1th', name: '1 Thessalonians', chapters: 5 },
      { id: '2th', name: '2 Thessalonians', chapters: 3 },
      { id: '1ti', name: '1 Timothy', chapters: 6 },
      { id: '2ti', name: '2 Timothy', chapters: 4 },
      { id: 'tit', name: 'Titus', chapters: 3 },
      { id: 'phm', name: 'Philemon', chapters: 1 },
      { id: 'heb', name: 'Hebrews', chapters: 13 },
      { id: 'jam', name: 'James', chapters: 5 },
      { id: '1pe', name: '1 Peter', chapters: 5 },
      { id: '2pe', name: '2 Peter', chapters: 3 },
      { id: '1jo', name: '1 John', chapters: 5 },
      { id: '2jo', name: '2 John', chapters: 1 },
      { id: '3jo', name: '3 John', chapters: 1 },
      { id: 'jud', name: 'Jude', chapters: 1 },
      { id: 'rev', name: 'Revelation', chapters: 22 }
    ]
  },
  yo: {
    old: [
      { id: 'gen', name: 'Jẹ́nẹ́sísì', chapters: 50 },
      { id: 'exo', name: 'Ẹ́kísódù', chapters: 40 },
      { id: 'lev', name: 'Léfítíkù', chapters: 27 },
      { id: 'num', name: 'Nọ́ńbà', chapters: 36 },
      { id: 'deu', name: 'Diutarónómì', chapters: 34 },
      { id: 'jos', name: 'Jóṣúà', chapters: 24 },
      { id: 'jud', name: 'Onídàájọ́', chapters: 21 },
      { id: 'rut', name: 'Rúùtù', chapters: 4 },
      { id: '1sa', name: '1 Sámúẹ́lì', chapters: 31 },
      { id: '2sa', name: '2 Sámúẹ́lì', chapters: 24 },
      { id: '1ki', name: '1 Àwọn Ọba', chapters: 22 },
      { id: '2ki', name: '2 Àwọn Ọba', chapters: 25 },
      { id: '1ch', name: '1 Kíróníkà', chapters: 29 },
      { id: '2ch', name: '2 Kíróníkà', chapters: 36 },
      { id: 'ezr', name: 'Ẹ́sírà', chapters: 10 },
      { id: 'neh', name: 'Nehemáyà', chapters: 13 },
      { id: 'est', name: 'Ẹ́sítà', chapters: 10 },
      { id: 'job', name: 'Jóòbù', chapters: 42 },
      { id: 'psa', name: 'Sáàmù', chapters: 150 },
      { id: 'pro', name: 'Òwe', chapters: 31 },
      { id: 'ecc', name: 'Oníwàásù', chapters: 12 },
      { id: 'sos', name: 'Orin Sólómọ́nì', chapters: 8 },
      { id: 'isa', name: 'Aísáyà', chapters: 66 },
      { id: 'jer', name: 'Jeremáyà', chapters: 52 },
      { id: 'lam', name: 'Ìdárò Jeremáyà', chapters: 5 },
      { id: 'eze', name: 'Ẹ́síkíẹ́lì', chapters: 48 },
      { id: 'dan', name: 'Dáníẹ́lì', chapters: 12 },
      { id: 'hos', name: 'Hósíà', chapters: 14 },
      { id: 'joe', name: 'Jóẹ́lì', chapters: 3 },
      { id: 'amo', name: 'Ámọ́sì', chapters: 9 },
      { id: 'oba', name: 'Ọbadáyà', chapters: 1 },
      { id: 'jon', name: 'Jónà', chapters: 4 },
      { id: 'mic', name: 'Míkà', chapters: 7 },
      { id: 'nah', name: 'Náhúmù', chapters: 3 },
      { id: 'hab', name: 'Hábákúkù', chapters: 3 },
      { id: 'zep', name: 'Sẹfanáyà', chapters: 3 },
      { id: 'hag', name: 'Hágáì', chapters: 2 },
      { id: 'zec', name: 'Sekaráyà', chapters: 14 },
      { id: 'mal', name: 'Málákì', chapters: 4 }
    ],
    new: [
      { id: 'mat', name: 'Mátíù', chapters: 28 },
      { id: 'mar', name: 'Máàkù', chapters: 16 },
      { id: 'luk', name: 'Lúùkù', chapters: 24 },
      { id: 'joh', name: 'Jòhánù', chapters: 21 },
      { id: 'act', name: 'Ìṣe Àwọn Àpọ́sítélì', chapters: 28 },
      { id: 'rom', name: 'Rómù', chapters: 16 },
      { id: '1co', name: '1 Kọ́ríńtì', chapters: 16 },
      { id: '2co', name: '2 Kọ́ríńtì', chapters: 13 },
      { id: 'gal', name: 'Gálátíà', chapters: 6 },
      { id: 'eph', name: 'Éfésù', chapters: 6 },
      { id: 'phi', name: 'Fílípì', chapters: 4 },
      { id: 'col', name: 'Kólósè', chapters: 4 },
      { id: '1th', name: '1 Tẹsalóníkà', chapters: 5 },
      { id: '2th', name: '2 Tẹsalóníkà', chapters: 3 },
      { id: '1ti', name: '1 Tímótì', chapters: 6 },
      { id: '2ti', name: '2 Tímótì', chapters: 4 },
      { id: 'tit', name: 'Títù', chapters: 3 },
      { id: 'phm', name: 'Fílémónì', chapters: 1 },
      { id: 'heb', name: 'Hébérù', chapters: 13 },
      { id: 'jam', name: 'Jákọ́bù', chapters: 5 },
      { id: '1pe', name: '1 Pétérù', chapters: 5 },
      { id: '2pe', name: '2 Pétérù', chapters: 3 },
      { id: '1jo', name: '1 Jòhánù', chapters: 5 },
      { id: '2jo', name: '2 Jòhánù', chapters: 1 },
      { id: '3jo', name: '3 Jòhánù', chapters: 1 },
      { id: 'jud', name: 'Júdà', chapters: 1 },
      { id: 'rev', name: 'Ìfihàn', chapters: 22 }
    ]
  }
};
